### ISSUE TITLE
Failed tests: undefined symbol: fribidi_unicode_version

### ISSUE THREAD

**Issue by doronbehar** [mkamensky/Text-Bidi#9] opened 2019-03-24 06:26 UTC
Hello Moshe,

I'm trying to compile this Perl module and I'm getting this output for `make test`:
```
t/00-version.t ......... Can't load '/var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so' for module Text::Bidi::private: /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so: undefined symbol: fribidi_unicode_version at /usr/lib/perl5/5.28/core_perl/DynaLoader.pm line 193.
 at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi/private.pm line 13.
Compilation failed in require at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
BEGIN failed--compilation aborted at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
Compilation failed in require at t/00-version.t line 14.
BEGIN failed--compilation aborted at t/00-version.t line 14.
# Looks like your test exited with 2 before it could output anything.
t/00-version.t ......... Dubious, test returned 2 (wstat 512, 0x200)
Failed 1/1 subtests
t/is_bidi.t ............ Can't load '/var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so' for module Text::Bidi::private: /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so: undefined symbol: fribidi_unicode_version at /usr/lib/perl5/5.28/core_perl/DynaLoader.pm line 193.
 at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi/private.pm line 13.
Compilation failed in require at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
BEGIN failed--compilation aborted at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
Compilation failed in require at t/is_bidi.t line 5.
BEGIN failed--compilation aborted at t/is_bidi.t line 5.
# Looks like your test exited with 2 before it could output anything.
t/is_bidi.t ............ Dubious, test returned 2 (wstat 512, 0x200)
Failed 3/3 subtests
t/shape.t .............. Can't load '/var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so' for module Text::Bidi::private: /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so: undefined symbol: fribidi_unicode_version at /usr/lib/perl5/5.28/core_perl/DynaLoader.pm line 193.
 at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi/private.pm line 13.
Compilation failed in require at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
BEGIN failed--compilation aborted at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
Compilation failed in require at t/shape.t line 5.
BEGIN failed--compilation aborted at t/shape.t line 5.
# Looks like your test exited with 2 before it could output anything.
t/shape.t .............. Dubious, test returned 2 (wstat 512, 0x200)
Failed 3/3 subtests
t/ucd.t ................ Can't load '/var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so' for module Text::Bidi::private: /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/arch/auto/Text/Bidi/private/private.so: undefined symbol: fribidi_unicode_version at /usr/lib/perl5/5.28/core_perl/DynaLoader.pm line 193.
 at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi/private.pm line 13.
Compilation failed in require at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
BEGIN failed--compilation aborted at /var/packages/archlinux/sources/perl-text-bidi/src/Text-Bidi-2.15/blib/lib/Text/Bidi.pm line 14.
Compilation failed in require at t/ucd.t line 50.
BEGIN failed--compilation aborted at t/ucd.t line 50.
t/ucd.t ................ Dubious, test returned 2 (wstat 512, 0x200)

```

As we can see, with fribidi version 1.0.5, we always get `undefined symbol: fribidi_unicode_version`. I don't know if it's related to #8 or not because the errors here are not in compile time but in tests and usage.

I hope you'll find the time to fix this please, thanks.

**Comment by moham96** [comment] 2019-05-01 19:03
Hi,
I'm also affected by this problem.
@mkamensky  please  take a look at this

Thanks

**Comment by mkamensky** [comment] 2019-05-01 21:36
Hi,

I missed this, sorry, but I cannot reproduce this. Could you tell me if the output of

    readelf -s /usr/lib/libfribidi.so

includes `fribidi_unicode_version`?

**Comment by moham96** [comment] 2019-05-02 00:01
@mkamensky no it doesn't

```
[mohammad@manjaro  ~]$ readelf -s /usr/lib/libfribidi.so.0.4.0|grep -c fribidi_unicode_version
0
```

**Comment by doronbehar** [comment] 2019-05-08 19:01
Wow.. Seems this issue should be consulted with an Arch Linux maintainer. I've tested this with the Arch build system and manually with the git repo and I can reproduce this if I set the following environmental variables before running `meson build && ninja -C build`: 

```sh
export CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
export CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"
export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
```

These are the default values used in `/etc/makepkg.conf` and from what I understand they are supposed to provide some default optimizations which shouldn't harm any other program using the compiled program / library.

One more piece of information which might be useful for us here at Text-Bidi:

When I ran `readelf -s libfribidi.so | grep -i version`. I got this output with the mentioned environmental variables **not set**:

```
    44: 000000000001f648     8 OBJECT  GLOBAL DEFAULT   21 fribidi_version_info
    33: 000000000001f640     8 OBJECT  LOCAL  DEFAULT   21 fribidi_unicode_version
   131: 000000000001f648     8 OBJECT  GLOBAL DEFAULT   21 fribidi_version_info
```

And this output with the environmental variables **set**:

```
    44: 000000000001f648     8 OBJECT  GLOBAL DEFAULT   21 fribidi_version_info
   131: 000000000001f648     8 OBJECT  GLOBAL DEFAULT   21 fribidi_version_info
```

I think we can just fix this issue by looking for `fribidi_version_info` instead of `fribidi_unicode_version`? Perhaps the later gets stripped in the Arch Build process because it's `LOCAL` and not `GLOBAL`? I'm not sure what that means but perhaps it's reasonable that a third party program would only look for symbols in a shared object from the later type..

**Comment by moham96** [comment] 2019-05-09 08:08
@doronbehar `fribidi_unicode_version` is not the same as `fribidi_version_info`, 
I think the reason that causes these symbols to be stripped is the use of `-O2` in the build flags, if you remove that then fribidi is built with `fribidi_unicode_version` included but it probably breaks the binary since i get a lot of warnings that i need to turn on optimizations.
I don't know if this should be reported in the archlinux bug tracker or the fribidi issues page

Regards

**Comment by moham96** [comment] 2019-05-25 09:12
This issue was resolved in fribidi upstream https://github.com/fribidi/fribidi/pull/110
@doronbehar if the above PR fixes the problem this issue can be closed

**Comment by doronbehar** [comment] 2019-05-25 09:35
Thanks for tracking this down!

**Closed** 2019-05-25 09:35 UTC

**Comment by mkamensky** [comment] 2019-05-25 10:37
Thank you both!
